# Generated by Django 5.2.1 on 2025-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_cvc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
