# Generated by Django 5.1.3 on 2026-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
