# Generated by Django 5.1.3 on 2026-08-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_product_out_of_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="out_of_stock",
            new_name="out_of_stock_since",
        ),
    ]
