# Generated by Django 5.1.3 on 2026-08-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_out_of_stock_product_out_of_stock_since"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_count",
        ),
    ]
