# Generated by Django 5.1.3 on 2026-08-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_orderitem_product_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.IntegerField(default=0),
        ),
    ]
