from django.utils.translation import gettext as _

_("Technik")
_("Phones")
_("PCs")
_("Apps & Games")
_("Gift Cards")
_("Baby")
_("Books")
_("Camera & Photo")
_("PC devices")
_("Toys & Games")
_("Clothing, Shoes & Jewelry")
_("Home & Kitchen")
_("Beauty & Personal Care")
_("Automotive & Car Parts")
_("Sim Racing & VR")
_("E-Bikes & Cycling")
_("Martial Arts & Combat Sports")
_("Pet Supplies")
_("Tools & Home Improvement")
_("Musical Instruments")
_("Groceries & Food")
_("Software & Web Development")
_("Office Products")
_("Garden & Outdoor")
_("Health & Household")
_("Furniture & Decor")
_("Industrial & Scientific")
