# Generated by Django 5.2.1 on 2025-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_order_cart_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
