# Generated by Django 5.1.3 on 2026-08-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_productview"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price_at_purchase",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.product",
            ),
        ),
    ]
