# Generated by Django 5.1.3 on 2026-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_orderitem_price_at_purchase_orderitem_product_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="out_of_stock",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
