# Generated by Django 5.1.3 on 2026-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_product_sold_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_de",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uk",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_de",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uk",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
