# Generated by Django 5.2.16 on 2026-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_product_description_de_product_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_uk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
